### ISSUE TITLE
Fill in information for services

### ISSUE THREAD

**Issue by spotlightishere** [WiiLink24/WiiLink24.github.io#16]
Currently, we have no copy within service descriptions.
The following services need a description:

- [ ] Wii Room
- [ ] Wii Room GO
- [ ] Digicam
- [ ] Demae
- [ ] Wii Fit Body Check Channel
- [ ] TV no Tomo

I've inserted dummy headers in the meantime, but feel free to modify accordingly if content can't fit!

**Comment by 6100m** [comment]
I'm on it Snoot! :)

**Comment by oscie57** [comment]
- [ ] YouTube
- [ ] Minna no Theatre Wii
- [ ] Nintendo Channel
- [ ] Everybody Votes Channel
- [ ] Mii Contest Channel
- [ ] Kirby TV Channel
- [ ] Set Personal Data

These ones also need to be done!

**Comment by 6100m** [comment]
> * [ ]  YouTube
> * [ ]  Minna no Theatre Wii
> * [ ]  Nintendo Channel
> * [ ]  Everybody Votes Channel
> * [ ]  Mii Contest Channel
> * [ ]  Kirby TV Channel
> * [ ]  Set Personal Data
> 
> These ones also need to be done!

I will more than likely PR these as soon as I can also (that is, if someone doesn't already beat me to the punch, heh) :)
