### ISSUE TITLE
digicam service page contains incorrect information

### ISSUE THREAD

**Issue by oscie57** [WiiLink24/WiiLink24.github.io#27]
https://www.wiilink24.com/services/digicam

> Digicam is telling me that my address is within “Dallas, TX”.
> This is the default address. Please change it via [Set Personal Data](https://www.wiilink24.com/services/spd).

Set Personal Data (Public release) does not contain address information, however the tester version does. Since Digicam is a publicly released service, it is probably in best interest to remove this line from the website.

**Comment by spotlightishere** [comment]
The [default template data](https://github.com/WiiLink24/set-personal-data/blob/fa6186181fd332e881c0aa8da0bc0e5bb41296f3/data/title/pd_decrypted.dat) shipping within the public release currently has this address hardcoded, which has lead to some confusion.

With the release of new SPD (slated soon, per triage project) hopefully this can be removed!
