### ISSUE TITLE
Veracode and stuff destroyed the website!

### ISSUE THREAD

**Issue by zurgeg** [WiiLink24/WiiLink24.github.io#3]
So uh it looks like [the webpage](wiilink24.github.io) has been removed? I used the "discontinuation" of the webpage to give a reason for it. I'm gonna ping @6100m to see if he knows how to solve it...
Screenshot:
![image](https://user-images.githubusercontent.com/46549042/95770601-a8614f80-0c87-11eb-83e2-2dfbba327b1e.png)

**Comment by 6100m** [comment]
Oh no... Don't worry, I will fix that :)

**Comment by zurgeg** [comment]
Ok!

**Comment by zurgeg** [comment]
Oh boy... @6100m it doesn't look like that fixed it...

**Comment by 6100m** [comment]
Ok, that should've fixed it, custom redirection engine is actually suprisingly almost done, I just have to work out some globalizing of variables and it's done. But don't worry, I would wait 5 mins, github takes time to update itself. If not, I will see what's happening with it 😉

**Comment by 6100m** [comment]
Yeah, that current redirection engine won't be there for long.

**Comment by zurgeg** [comment]
No you put the commit in the wrong place, you wanna put it in `_layouts/default.html`

**Comment by zurgeg** [comment]
Yeah the site is still down @6100m.

**Comment by 6100m** [comment]
I did :) Basically, that index.html routes to _layouts/default.html, its a pointer :) Gimme about 5 mins, I will look into it? :)

**Comment by 6100m** [comment]
Ok, it was just on the wrong branch, no worries :)

**Comment by zurgeg** [comment]
Ah, makes a lot more sense.
But then wouldn't we wanna point it to wiilink24.github.io? Because that _layouts/default.html is just a Jninja template.

**Comment by zurgeg** [comment]
Also we have wiilink24.com now!

**Comment by 6100m** [comment]
Ok, clone it and run cname.bat, that will get you a CNAME file you upload to the root 👍 

I actually am really excited to use it, can I be co-admin of wiilink24.com? :)

**Comment by zurgeg** [comment]
@6100m ask @a32bitmint for that stuff.

**Comment by zurgeg** [comment]
You just deleted the custom layout by accident @6100m. Now our images and stuff won't display on the page...

**Comment by 6100m** [comment]
I will, tell him I said thank you, Im doing online school atm, and I am doing some of this with my web design class too to kill two birds with one stone :) By the way, reason I put that index.html is because it won't route to it by default. As for that, don't worry, I will fix it, I am struggling a bit, sorry about that haha.

**Comment by 6100m** [comment]
Fixed that bit, it SHOULD load now. Be sure to upload that CNAME file the script generated into the root of this repo, that will route it to wiilink24.com :)

**Comment by zurgeg** [comment]
So it routes it to the google site right?

**Comment by 6100m** [comment]
It'll route to wiilink24.com, Im not sure where the google site is haha. But yeah, that should get github to route this repo to wiilink24.com.

**Comment by zurgeg** [comment]
Oh you can just set a custom domain from settings...

**Comment by zurgeg** [comment]
> It'll route to wiilink24.com, Im not sure where the google site is haha. But yeah, that should get github to route this repo to wiilink24.com.

@6100m on WiiLink24.com

**Comment by zurgeg** [comment]
Oh great... the entire page just broke down. Okay... let's get this page redirected!

**Comment by 6100m** [comment]
Yep, the script will make the file you upload to the root of the repo to redirect to wiilink24.com :)

**Comment by zurgeg** [comment]
Welp! Bye bye broken GH Page ;)

**Comment by zurgeg** [comment]
Should we archive this repo now?

**Comment by zurgeg** [comment]
@6100m keep in mind that everything redirects to either 404 not found (idk why) or wiilink24.com...
