### ISSUE TITLE
I should note, you must also do a record on the actual registrar itself. Fix?

### ISSUE THREAD

**Issue by 6100m** [WiiLink24/WiiLink24.github.io#4]
What I mean is, https://www.youtube.com/watch?v=mPGi1IHQxFM use this guide to create the record on the com registar you use, don't worry about the final part where you make the CNAME file in the repo, you've already done that. But making that file is only half of it, you have to also create the record on the registar itself using this guide.

**Comment by zurgeg** [comment]
@6100m a32bitmint is hosting the google site on there.

**Comment by 6100m** [comment]
Yeah, but you need to add the record from the guide to the registar as well to complete the job :) It consists of two parts:
1: Adding the record from the guide to your registar (Freenom, google sites, godaddy, etc.)
2: Adding the CNAME record to the root of this repo (which you have already done) :)

**Comment by 6100m** [comment]
@spotlightishere Hey spotlight, you rerember how to add it to the registar right? Just wondering, as I am on a school computer so I can't get on Discord right now to show you guys how haha. :)

**Comment by 6100m** [comment]
Your site's DNS settings are using a custom subdomain, wiilink24.com, that's set up with an AAAA record. GitHub Pages currently does not support IPv6. For more information, see https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/.

It will say this near the bottom in settings :)

**Comment by spotlightishere** [comment]
Sure thing - we set up the domain to use Google Sites per some discussion in development, are we favoring this site instead?

**Comment by 6100m** [comment]
I think so, but I am worried we can't do Ajax, but hopefully it works out :)

**Comment by spotlightishere** [comment]
We currently have the site configured to the one made on Google Sites.. let's discuss in development later today, possibly we could figure out how to combine info or integrate the two?

**Comment by 6100m** [comment]
Alr, that I can do :)
